export { default as Delete } from './Delete'
export { default as Update } from './Update'
export { default as Create } from './Create'
export { default as UpdateCreate } from './UpdateCreate'
export { default as Alerts } from './Alerts'